### ISSUE TITLE
Please add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by easternbloc** [UKHomeOffice/eslint-config-homeoffice#8]
:heart:

**Comment by merlinc** [comment]
Is there a current template anywhere to use as a basis?

**Comment by easternbloc** [comment]
you can have this blurb: https://github.com/UKHomeOffice/brp_app/blob/master/CONTRIBUTING.md

or this blurb:

https://github.com/UKHomeOffice/hof/blob/master/CONTRIBUTING.md

**Comment by easternbloc** [comment]
I believe the latter is found more frequently around HO. The first one I made up based on feelings

**Comment by merlinc** [comment]
I've chosen the 2nd one, with an updated code of conduct from Contributor Covenant. 

We can more detailed instructions later if required.

**Comment by easternbloc** [comment]
Cool :+1:
